In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

#設定字體為標楷體'DFKai-sb':
from pylab import *
mpl.rcParams['font.sans-serif'] = ['DFKai-sb']

In [103]:
f1 = open('H:\\LabData\\DATA\\蚊子資料(需要更新)\\2013-2015全區統整(時間編號).csv','r')
data_list = []
for i in f1.readlines():
    data = i.strip()
    data = data.split(',')
    data_list.append(data)
f1.close()
MosData = pd.DataFrame(data_list[1:],columns=data_list[0])
MosData.head()

,合併用,時間編號,月,年,區,里,PosHH,PosHHAeg,ConIn,ConOut,...,HIAeg,HILv,HILvAeg,CI,CILv,LI,LILv,Pupa,AI,Con100HH
0,220132三民區安生里,2,2,2013,三民區,安生里,0,0,15,18,...,0,0,0,0,0,0,0,0,0,0
1,220132三民區安邦里,2,2,2013,三民區,安邦里,0,0,14,15,...,0,0,0,0,0,0,0,0,0,0
2,220132三民區安宜里,2,2,2013,三民區,安宜里,0,0,17,21,...,0,0,0,0,0,0,0,0,0,0
3,220132三民區安泰里,2,2,2013,三民區,安泰里,0,0,24,5,...,0,0,0,0,0,0,0,0,0,0
4,220132三民區安發里,2,2,2013,三民區,安發里,0,0,12,15,...,0,0,0,0,0,0,0,0,0,0

In [113]:
f1 = open('H:\\LabData\\DATA\\登革熱個案\\2013-2014登革熱發生數(時間編號).csv','r')
data_list = []
for i in f1.readlines():
    data = i.strip()
    data = data.split(',')
    data_list.append(data)
f1.close()
incidata = pd.DataFrame(data_list[1:],columns=data_list[0])
print(incidata.head())
Timelag = pd.DataFrame(list(map(int,list(incidata.ix[:,1]))))-12
Timelag = pd.DataFrame(list(map(str,list(Timelag.ix[:,0]))))
incidata['時間編號'] = Timelag
incidata.head()

             合併用 時間編號    區    里     年  月 個案數   人口數 發生率
0  1320141三民區力行里   13  三民區  力行里  2014  1   0  1315   0
1  1420142三民區力行里   14  三民區  力行里  2014  2   0  1315   0
2  1520143三民區力行里   15  三民區  力行里  2014  3   0  1315   0
3  1620144三民區力行里   16  三民區  力行里  2014  4   0  1315   0
4  1720145三民區力行里   17  三民區  力行里  2014  5   0  1315   0

             合併用 時間編號    區    里     年  月 個案數   人口數 發生率
0  1320141三民區力行里    1  三民區  力行里  2014  1   0  1315   0
1  1420142三民區力行里    2  三民區  力行里  2014  2   0  1315   0
2  1520143三民區力行里    3  三民區  力行里  2014  3   0  1315   0
3  1620144三民區力行里    4  三民區  力行里  2014  4   0  1315   0
4  1720145三民區力行里    5  三民區  力行里  2014  5   0  1315   0

In [114]:
MergeData = pd.merge(MosData,incidata, on=['時間編號','區','里'])
#MergeData.head(10)

In [115]:
MergeData.to_csv('H:\\LabData\DATA\\日期\\20170602time資料\\2013-2014登革熱發生數(timelag12).csv')